module.exports = {
  Ping: require('./ping'),
  Base: require('./base'),
  Clan: require('./clan'),
  AddBase: require('./addbase'),
  RemoveBase: require('./removebase'),
  AddClan: require('./addClan'),
  RemoveClan: require('./removeClan'),
  SetRequirements: require('./setRequirements'),
  NeedClan: require('./needClan'),
  Help: require('./help'),
  StopSearching: require('./stopSearching'),
  StartSearching: require('./startSearching'),
  DeleteRequirements: require('./deleteRequirements'),
  Update: require('./update'),
  UpdateAll: require('./updateAll'),
  showRequirements: require('./showRequirements'),
  CheckBase: require('./checkBase'),
  Invite: require('./invite'),
  nos: require('./nos')
}