module.exports = {
    /* "bronze 3": 1,
    "bronze 2": 2,
    "bronze 1": 3,
    "silver 3": 4,
    "silver 2": 5,
    "silver 1": 6,
    "gold 3": 7,
    "gold 2": 8,
    "gold 1": 9,
    "crystal 3": 10,
    "crystal 2": 11,
    "crystal 1": 12,
    "master 3": 13,
    "master 2": 14,
    "master 1": 15,
    "champion 3": 16,
    "champion 2": 17,
    "champion 1": 18, */
    "Unranked": 0,
    "Bronze League III": 1,
    "Bronze League II": 2,
    "Bronze League I": 3,
    "Silver League III": 4,
    "Silver League II": 5,
    "Silver League I": 6,
    "Gold League III": 7,
    "Gold League II": 8,
    "Gold League I": 9,
    "Crystal League III": 10,
    "Crystal League II": 11,
    "Crystal League I": 12,
    "Master League III": 13,
    "Master League II": 14,
    "Master League I": 15,
    "Champion League III": 16,
    "Champion League II": 17,
    "Champion League I": 18
}